from __future__ import annotations

import csv
import io
import json
import os
import shutil
import subprocess
import time
import zipfile
from pathlib import Path, PurePosixPath
from typing import Any

from .util import PROJECT_ROOT, is_within, sha256_file, write_json
from .xunity import offline_config


BEPINEX_ARCHIVE = "BepInEx-Unity.IL2CPP-win-x64-6.0.0-pre.2.zip"
XUNITY_ARCHIVE = "XUnity.AutoTranslator-BepInEx-IL2CPP-5.6.1.zip"
RICH_TEXT_FIX_PLUGIN = PROJECT_ROOT / "tools" / "runtime" / "ArknightsLocalization.RichTextFix.dll"
RICH_TEXT_FIX_DESTINATION = PurePosixPath(
    "BepInEx/plugins/ArknightsLocalization/ArknightsLocalization.RichTextFix.dll"
)
COMPONENT_HASHES = {
    BEPINEX_ARCHIVE: "616ec7eb06cf11b2a0000e8fcef04d1b12bb58e84a2e0bdac9523234fc193ceb",
    XUNITY_ARCHIVE: "9d6b26e9d4957459bdb64b6d4852edb39cd5e8d31c28e0a157cefd6510ada811",
}

AUTO_TRANSLATOR_CONFIG_PATH = "BepInEx/config/AutoTranslatorConfig.ini"
MANAGED_RUNTIME_ROOTS = ("BepInEx", "dotnet")
# BepInEx/Il2CppInterop and XUnity create these after the first game launch.
# They cannot be present in the staging manifest, but are still owned runtime
# output when this toolkit created the corresponding BepInEx installation.
GENERATED_RUNTIME_TREES = (
    "BepInEx/cache",
    "BepInEx/interop",
    "BepInEx/unity-libs",
)
GENERATED_RUNTIME_FILES = (
    "BepInEx/ErrorLog.log",
    "BepInEx/LogOutput.log",
    # XUnity expands the staged offline config with defaults/migration fields
    # on first launch, so its hash no longer matches the installation record.
    AUTO_TRANSLATOR_CONFIG_PATH,
    "BepInEx/config/BepInEx.cfg",
    "BepInEx/config/gravydevsupreme.xunity.resourceredirector.cfg",
    "BepInEx/Translation/zh/Text/_AutoGeneratedTranslations.txt",
    "BepInEx/Translation/zh/Text/_Postprocessors.txt",
    "BepInEx/Translation/zh/Text/_Preprocessors.txt",
    "BepInEx/Translation/zh/Text/_Substitutions.txt",
    # Fixed pack names used by every toolkit release. They are normally
    # tracked by the install manifest, but older repair installs could restore
    # a localized copy and then discard that manifest during uninstall.
    "BepInEx/Translation/zh/Text/00_i18n.txt",
    "BepInEx/Translation/zh/Text/20_tables.txt",
    "BepInEx/Translation/zh/Text/30_story.txt",
)
BACKUP_STORE_NAME = ".arklocalizer-backup"


def validate_game_directory(game_dir: Path) -> Path:
    """Validate the two stable client markers without importing extraction dependencies."""
    game_dir = game_dir.resolve()
    if not (game_dir / "Arknights.exe").is_file():
        raise FileNotFoundError(f"Arknights.exe not found below {game_dir}")
    if not (game_dir / "Arknights_Data").is_dir():
        raise FileNotFoundError(f"Arknights_Data not found below {game_dir}")
    return game_dir


def _validate_archive(path: Path) -> None:
    expected = COMPONENT_HASHES.get(path.name)
    if expected is None:
        raise ValueError(f"Unrecognized component archive: {path.name}")
    actual = sha256_file(path)
    if actual != expected:
        raise ValueError(f"SHA-256 mismatch for {path.name}: {actual}")


def _safe_zip_member(name: str) -> PurePosixPath:
    path = PurePosixPath(name.replace("\\", "/"))
    if path.is_absolute() or ".." in path.parts:
        raise ValueError(f"Unsafe archive path: {name}")
    return path


def _safe_manifest_path(name: str) -> PurePosixPath:
    path = _safe_zip_member(name)
    if not path.parts:
        raise ValueError("Empty manifest path")
    return path


def _remove_owned_tree(path: Path, game_dir: Path) -> None:
    """Remove one explicitly owned generated tree without following links."""
    if not is_within(path, game_dir):
        raise ValueError(f"Managed cleanup path escaped game directory: {path}")
    if path.is_symlink():
        path.unlink()
        return
    if not path.is_dir():
        if path.exists():
            path.unlink()
        return
    for child in path.iterdir():
        if child.is_symlink() or child.is_file():
            child.unlink()
        elif child.is_dir():
            _remove_owned_tree(child, game_dir)
        else:
            raise OSError(f"Unsupported managed runtime entry: {child}")
    path.rmdir()


def _prune_empty_directories(root: Path, game_dir: Path) -> list[str]:
    if not root.exists() or root.is_symlink() or not root.is_dir():
        return []
    if not is_within(root, game_dir):
        raise ValueError(f"Managed root escaped game directory: {root}")
    removed: list[str] = []
    directories = [path for path in root.rglob("*") if path.is_dir() and not path.is_symlink()]
    for path in sorted(directories, key=lambda item: len(item.parts), reverse=True):
        try:
            path.rmdir()
            removed.append(path.relative_to(game_dir).as_posix())
        except OSError:
            pass
    try:
        root.rmdir()
        removed.append(root.relative_to(game_dir).as_posix())
    except OSError:
        pass
    return removed


def _remove_backup_store(game_dir: Path, *, keep: Path | None = None) -> list[str]:
    """Remove toolkit-owned backup generations without following links."""
    store = game_dir / BACKUP_STORE_NAME
    if not store.exists():
        return []
    if not is_within(store, game_dir):
        raise ValueError(f"Backup store escaped game directory: {store}")
    keep_resolved = keep.resolve() if keep is not None else None
    removed: list[str] = []
    if store.is_symlink() or not store.is_dir():
        raise OSError(f"Backup store is not a regular directory: {store}")
    for child in store.iterdir():
        if keep_resolved is not None and child.resolve() == keep_resolved:
            continue
        relative = child.relative_to(game_dir).as_posix()
        _remove_owned_tree(child, game_dir)
        removed.append(relative)
    try:
        store.rmdir()
        removed.append(BACKUP_STORE_NAME)
    except OSError:
        pass
    return removed


def inspect_orphaned_runtime(game_dir: Path) -> dict[str, Any]:
    """Recognize generated leftovers from older uninstall manifests safely."""
    game_dir = validate_game_directory(game_dir)
    if (game_dir / "ArknightsLocalizationToolkit.install.json").is_file():
        return {"orphaned": False, "unknown_files": [], "generated_files": []}

    generated_tree_parts = [PurePosixPath(value).parts for value in GENERATED_RUNTIME_TREES]
    generated_files = {PurePosixPath(value).parts for value in GENERATED_RUNTIME_FILES}
    recognized: list[str] = []
    unknown: list[str] = []
    roots_present = False
    for root_name in MANAGED_RUNTIME_ROOTS:
        root = game_dir / root_name
        if not root.exists():
            continue
        roots_present = True
        if root.is_symlink() or not root.is_dir():
            unknown.append(root_name)
            continue
        for path in root.rglob("*"):
            if path.is_dir() and not path.is_symlink():
                continue
            relative = PurePosixPath(path.relative_to(game_dir).as_posix())
            parts = relative.parts
            known = parts in generated_files or any(
                parts[: len(prefix)] == prefix for prefix in generated_tree_parts
            )
            (recognized if known else unknown).append(relative.as_posix())

    # Doorstop/root loader files cannot be safely attributed without a
    # manifest. Their presence means this is a real foreign/modified install.
    for name in ("winhttp.dll", ".doorstop_version", "doorstop_config.ini"):
        if (game_dir / name).exists():
            unknown.append(name)
    backup_store_present = (game_dir / BACKUP_STORE_NAME).exists()
    return {
        "orphaned": (
            (roots_present and bool(recognized or (game_dir / "BepInEx").is_dir()))
            or backup_store_present
        )
        and not unknown,
        "unknown_files": sorted(unknown),
        "generated_files": sorted(recognized),
        "backup_store_present": backup_store_present,
    }


def cleanup_orphaned_runtime(game_dir: Path, *, apply: bool = False) -> dict[str, Any]:
    game_dir = validate_game_directory(game_dir)
    running_processes = _running_game_processes(game_dir)
    if apply and running_processes:
        raise RuntimeError("Arknights.exe is running; close the game before uninstalling")
    inspection = inspect_orphaned_runtime(game_dir)
    if not inspection["orphaned"]:
        raise FileNotFoundError("No safely recognizable old ArknightsLocalizationToolkit residue found")
    actions: list[dict[str, str]] = []
    for relative_name in GENERATED_RUNTIME_TREES:
        destination = game_dir.joinpath(*PurePosixPath(relative_name).parts)
        if destination.exists():
            actions.append({"path": relative_name, "action": "remove_generated_tree"})
    for relative_name in GENERATED_RUNTIME_FILES:
        destination = game_dir.joinpath(*PurePosixPath(relative_name).parts)
        if destination.exists():
            actions.append({"path": relative_name, "action": "remove_generated"})
    pruned: list[str] = []
    if apply:
        for action in actions:
            destination = game_dir.joinpath(*PurePosixPath(action["path"]).parts)
            if action["action"] == "remove_generated_tree":
                _remove_owned_tree(destination, game_dir)
            elif destination.is_symlink() or destination.is_file():
                destination.unlink()
        for root_name in MANAGED_RUNTIME_ROOTS:
            pruned.extend(_prune_empty_directories(game_dir / root_name, game_dir))
        pruned.extend(_remove_backup_store(game_dir))
    return {
        "game_directory": str(game_dir),
        "running_processes": running_processes,
        "applied": apply,
        "legacy_residue": True,
        "actions": actions,
        "pruned_directories": pruned,
    }


def _extract_zip(
    archive: Path,
    destination: Path,
    *,
    skip_prefixes: tuple[str, ...] = (),
) -> None:
    with zipfile.ZipFile(archive) as package:
        for info in package.infolist():
            path = _safe_zip_member(info.filename)
            normalized = path.as_posix().casefold()
            if info.is_dir() or any(normalized.startswith(prefix.casefold()) for prefix in skip_prefixes):
                continue
            target = destination.joinpath(*path.parts)
            target.parent.mkdir(parents=True, exist_ok=True)
            with package.open(info) as source, target.open("wb") as output:
                shutil.copyfileobj(source, output)


def stage_runtime(
    components_root: Path,
    pack_root: Path,
    output_root: Path,
    source_locale: str,
    *,
    font_bundle: Path | None = None,
    rich_text_plugin: Path = RICH_TEXT_FIX_PLUGIN,
) -> dict[str, Any]:
    if output_root.exists() and any(output_root.iterdir()):
        raise FileExistsError(f"Staging directory is not empty: {output_root}")
    output_root.mkdir(parents=True, exist_ok=True)

    bepinex = components_root / BEPINEX_ARCHIVE
    xunity = components_root / XUNITY_ARCHIVE
    for archive in (bepinex, xunity):
        if not archive.is_file():
            raise FileNotFoundError(archive)
        _validate_archive(archive)

    _extract_zip(bepinex, output_root)
    _extract_zip(
        xunity,
        output_root,
        skip_prefixes=("BepInEx/plugins/XUnity.AutoTranslator/Translators/",),
    )

    if not rich_text_plugin.is_file():
        raise FileNotFoundError(
            f"Rich-text companion plugin not found: {rich_text_plugin}. "
            "Build plugins/ArknightsLocalization.RichTextFix and copy its DLL to tools/runtime first."
        )
    plugin_destination = output_root.joinpath(*RICH_TEXT_FIX_DESTINATION.parts)
    plugin_destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(rich_text_plugin, plugin_destination)

    source_text = pack_root / "Translation" / "zh" / "Text"
    if not source_text.is_dir():
        raise FileNotFoundError(f"Translation pack not found: {source_text}")
    destination_text = output_root / "BepInEx" / "Translation" / "zh" / "Text"
    destination_text.mkdir(parents=True, exist_ok=True)
    for source in source_text.glob("*.txt"):
        shutil.copy2(source, destination_text / source.name)

    font_name = ""
    if font_bundle is not None:
        if not font_bundle.is_file():
            raise FileNotFoundError(font_bundle)
        font_name = font_bundle.name
        shutil.copy2(font_bundle, output_root / font_name)

    config = output_root / "BepInEx" / "config" / "AutoTranslatorConfig.ini"
    config.parent.mkdir(parents=True, exist_ok=True)
    config.write_text(offline_config(source_locale, font_name), encoding="utf-8", newline="\n")

    files = []
    for path in sorted(output_root.rglob("*")):
        if path.is_file() and path.name != "ARKLOCALIZER_MANIFEST.json":
            files.append(
                {
                    "path": path.relative_to(output_root).as_posix(),
                    "bytes": path.stat().st_size,
                    "sha256": sha256_file(path),
                }
            )
    manifest = {
        "tool": "ArknightsLocalizationToolkit",
        "source_locale": source_locale,
        "offline_only": True,
        "components": [
            {"name": BEPINEX_ARCHIVE, "sha256": COMPONENT_HASHES[BEPINEX_ARCHIVE]},
            {"name": XUNITY_ARCHIVE, "sha256": COMPONENT_HASHES[XUNITY_ARCHIVE]},
        ],
        "font": font_name or None,
        "rich_text_plugin": {
            "path": RICH_TEXT_FIX_DESTINATION.as_posix(),
            "sha256": sha256_file(plugin_destination),
        },
        "files": files,
    }
    write_json(output_root / "ARKLOCALIZER_MANIFEST.json", manifest)
    return manifest


def _running_game_processes(game_dir: Path) -> list[dict[str, str]]:
    """Conservatively detect the Windows game process before changing files."""
    if os.name != "nt":
        return []
    executable = (game_dir / "Arknights.exe").name
    completed = subprocess.run(
        ["tasklist.exe", "/FI", f"IMAGENAME eq {executable}", "/FO", "CSV", "/NH"],
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    running: list[dict[str, str]] = []
    for row in csv.reader(io.StringIO(completed.stdout)):
        if len(row) >= 2 and row[0].casefold() == executable.casefold():
            running.append({"image": row[0], "pid": row[1]})
    return running


def plan_install(staging_root: Path, game_dir: Path) -> dict[str, Any]:
    game_dir = validate_game_directory(game_dir)
    manifest = json.loads((staging_root / "ARKLOCALIZER_MANIFEST.json").read_text(encoding="utf-8"))
    actions = []
    for item in manifest["files"]:
        relative = PurePosixPath(item["path"])
        if relative.is_absolute() or ".." in relative.parts:
            raise ValueError(f"Unsafe staged file: {relative}")
        source = staging_root.joinpath(*relative.parts)
        destination = game_dir.joinpath(*relative.parts)
        if not source.is_file():
            raise FileNotFoundError(source)
        staged_hash = sha256_file(source)
        if staged_hash != item["sha256"]:
            raise ValueError(f"Staged file hash mismatch: {source}")
        if destination.is_file():
            current_hash = sha256_file(destination)
            action = "unchanged" if current_hash == item["sha256"] else "replace"
        else:
            current_hash = None
            action = "create"
        actions.append(
            {
                "path": relative.as_posix(),
                "action": action,
                "current_sha256": current_hash,
                "staged_sha256": item["sha256"],
            }
        )
    return {
        "game_directory": str(game_dir),
        "running_processes": _running_game_processes(game_dir),
        "create": sum(item["action"] == "create" for item in actions),
        "replace": sum(item["action"] == "replace" for item in actions),
        "unchanged": sum(item["action"] == "unchanged" for item in actions),
        "actions": actions,
    }


def _manifest_owned_root(manifest: dict[str, Any], root_name: str) -> bool:
    root_state = manifest.get("managed_roots", {}).get(root_name)
    if isinstance(root_state, dict) and "existed_before" in root_state:
        return not bool(root_state["existed_before"])
    # Compatibility with manifests written before managed_roots existed. A
    # replaced file below a root proves that runtime tree predated installation.
    prefix = root_name.casefold() + "/"
    root_items = [
        item
        for item in manifest.get("files", [])
        if str(item.get("path", "")).casefold().startswith(prefix)
    ]
    return bool(root_items) and not any(
        item.get("previous_sha256") is not None for item in root_items
    )


def install_runtime(staging_root: Path, game_dir: Path, *, apply: bool = False) -> dict[str, Any]:
    plan = plan_install(staging_root, game_dir)
    if not apply:
        return plan
    if plan["running_processes"]:
        raise RuntimeError("Arknights.exe is running; close the game before installing")
    game_dir = Path(plan["game_directory"])
    timestamp = time.strftime("%Y%m%d-%H%M%S")
    backup_root = game_dir / BACKUP_STORE_NAME / timestamp
    suffix = 1
    while backup_root.exists():
        backup_root = game_dir / BACKUP_STORE_NAME / f"{timestamp}-{suffix:02d}"
        suffix += 1
    manifest = json.loads((staging_root / "ARKLOCALIZER_MANIFEST.json").read_text(encoding="utf-8"))
    install_path = game_dir / "ArknightsLocalizationToolkit.install.json"
    previous_manifest: dict[str, Any] | None = None
    previous_backup_root: Path | None = None
    previous_files: dict[str, dict[str, Any]] = {}
    if install_path.is_file():
        previous_manifest = json.loads(install_path.read_text(encoding="utf-8"))
        previous_backup_root = Path(previous_manifest["backup_root"])
        if not is_within(previous_backup_root, game_dir):
            raise ValueError(f"Previous backup root escaped game directory: {previous_backup_root}")
        previous_files = {
            str(item["path"]): item for item in previous_manifest.get("files", [])
        }

    staged_roots = {
        PurePosixPath(str(action["path"])).parts[0].casefold()
        for action in plan["actions"]
    }
    managed_roots: dict[str, dict[str, bool]] = {}
    for root_name in MANAGED_RUNTIME_ROOTS:
        if root_name.casefold() not in staged_roots:
            continue
        if previous_manifest is None:
            existed_before = (game_dir / root_name).exists()
        else:
            existed_before = not _manifest_owned_root(previous_manifest, root_name)
        managed_roots[root_name] = {"existed_before": existed_before}
    installed: list[dict[str, Any]] = []

    staged_paths = {str(action["path"]) for action in plan["actions"]}
    retired_actions: list[dict[str, str]] = []
    if previous_manifest is not None and previous_backup_root is not None:
        for relative_name, previous_item in previous_files.items():
            if relative_name in staged_paths:
                continue
            relative = _safe_manifest_path(relative_name)
            destination = game_dir.joinpath(*relative.parts)
            if not destination.is_file() or sha256_file(destination) != previous_item["sha256"]:
                retired_actions.append({"path": relative.as_posix(), "action": "skip_modified"})
                continue
            previous_sha = previous_item.get("previous_sha256")
            previous_backup = previous_backup_root.joinpath(*relative.parts)
            if previous_sha is None:
                destination.unlink()
                retired_actions.append({"path": relative.as_posix(), "action": "remove"})
            else:
                if (
                    previous_backup.is_symlink()
                    or not previous_backup.is_file()
                    or sha256_file(previous_backup) != previous_sha
                ):
                    raise FileNotFoundError(f"Original backup is missing or invalid: {previous_backup}")
                shutil.copy2(previous_backup, destination)
                retired_actions.append({"path": relative.as_posix(), "action": "restore"})

    for action in plan["actions"]:
        relative = PurePosixPath(action["path"])
        source = staging_root.joinpath(*relative.parts)
        destination = game_dir.joinpath(*relative.parts)
        previous_item = previous_files.get(relative.as_posix())
        previous_sha256 = action["current_sha256"]
        previous_is_current = (
            previous_item is not None
            and action["current_sha256"] == previous_item.get("sha256")
        )
        if previous_is_current:
            previous_sha256 = previous_item.get("previous_sha256")
            if previous_sha256 is not None:
                if previous_backup_root is None:
                    raise FileNotFoundError("Previous backup root is missing")
                previous_backup = previous_backup_root.joinpath(*relative.parts)
                if (
                    previous_backup.is_symlink()
                    or not previous_backup.is_file()
                    or sha256_file(previous_backup) != previous_sha256
                ):
                    raise FileNotFoundError(f"Original backup is missing or invalid: {previous_backup}")
                backup = backup_root.joinpath(*relative.parts)
                backup.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(previous_backup, backup)
        elif action["action"] in {"replace", "unchanged"}:
            backup = backup_root.joinpath(*relative.parts)
            backup.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(destination, backup)
        elif action["action"] == "create" and previous_item is not None:
            previous_sha256 = previous_item.get("previous_sha256")
            if previous_sha256 is not None:
                if previous_backup_root is None:
                    raise FileNotFoundError("Previous backup root is missing")
                previous_backup = previous_backup_root.joinpath(*relative.parts)
                if (
                    previous_backup.is_symlink()
                    or not previous_backup.is_file()
                    or sha256_file(previous_backup) != previous_sha256
                ):
                    raise FileNotFoundError(f"Original backup is missing or invalid: {previous_backup}")
                backup = backup_root.joinpath(*relative.parts)
                backup.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(previous_backup, backup)
        if action["action"] != "unchanged":
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)
        installed.append(
            {
                "path": relative.as_posix(),
                "sha256": sha256_file(destination),
                "previous_sha256": previous_sha256,
            }
        )

    install_manifest = {
        "schema": 2,
        "installed_at": timestamp,
        "backup_root": str(backup_root),
        "managed_roots": managed_roots,
        "staging_manifest": manifest,
        "files": installed,
    }
    write_json(game_dir / "ArknightsLocalizationToolkit.install.json", install_manifest)
    removed_backup_generations = _remove_backup_store(game_dir, keep=backup_root)
    plan["applied"] = True
    plan["backup_root"] = str(backup_root)
    plan["retired_actions"] = retired_actions
    plan["removed_backup_generations"] = removed_backup_generations
    return plan


def uninstall_runtime(game_dir: Path, *, apply: bool = False) -> dict[str, Any]:
    game_dir = validate_game_directory(game_dir)
    running_processes = _running_game_processes(game_dir)
    if apply and running_processes:
        raise RuntimeError("Arknights.exe is running; close the game before uninstalling")
    install_path = game_dir / "ArknightsLocalizationToolkit.install.json"
    if not install_path.is_file():
        return cleanup_orphaned_runtime(game_dir, apply=apply)
    manifest = json.loads(install_path.read_text(encoding="utf-8"))
    backup_root = Path(manifest["backup_root"])
    if not is_within(backup_root, game_dir):
        raise ValueError(f"Backup root escaped game directory: {backup_root}")

    actions: list[dict[str, str]] = []
    for item in manifest["files"]:
        relative = _safe_manifest_path(item["path"])
        destination = game_dir.joinpath(*relative.parts)
        backup = backup_root.joinpath(*relative.parts)
        previous_sha256 = item.get("previous_sha256")
        if destination.is_file() and sha256_file(destination) != item["sha256"]:
            action = "skip_modified"
        elif previous_sha256 is not None:
            if backup.is_symlink() or not backup.is_file():
                raise FileNotFoundError(f"Original backup is missing: {backup}")
            if sha256_file(backup) != previous_sha256:
                raise ValueError(f"Original backup hash mismatch: {backup}")
            action = "restore"
        elif destination.is_file() and sha256_file(destination) == item["sha256"]:
            action = "remove"
        elif destination.exists():
            action = "skip_modified"
        else:
            action = "already_absent"
        actions.append({"path": relative.as_posix(), "action": action})

    owned_roots: list[str] = []
    for root_name in MANAGED_RUNTIME_ROOTS:
        if _manifest_owned_root(manifest, root_name):
            owned_roots.append(root_name)

    for relative_name in GENERATED_RUNTIME_TREES:
        if PurePosixPath(relative_name).parts[0] not in owned_roots:
            continue
        destination = game_dir.joinpath(*PurePosixPath(relative_name).parts)
        if destination.exists():
            actions.append({"path": relative_name, "action": "remove_generated_tree"})
    for relative_name in GENERATED_RUNTIME_FILES:
        if PurePosixPath(relative_name).parts[0] not in owned_roots:
            continue
        destination = game_dir.joinpath(*PurePosixPath(relative_name).parts)
        if destination.exists():
            actions.append({"path": relative_name, "action": "remove_generated"})

    pruned: list[str] = []
    if apply:
        for action in actions:
            relative = _safe_manifest_path(action["path"])
            destination = game_dir.joinpath(*relative.parts)
            backup = backup_root.joinpath(*relative.parts)
            if action["action"] == "restore":
                destination.parent.mkdir(parents=True, exist_ok=True)
                os.replace(backup, destination)
            elif action["action"] == "remove":
                destination.unlink()
            elif action["action"] == "remove_generated_tree":
                _remove_owned_tree(destination, game_dir)
            elif action["action"] == "remove_generated" and (
                destination.is_file() or destination.is_symlink()
            ):
                destination.unlink()
        for root_name in owned_roots:
            pruned.extend(_prune_empty_directories(game_dir / root_name, game_dir))
        pruned.extend(_remove_backup_store(game_dir))
        install_path.unlink()
    return {
        "game_directory": str(game_dir),
        "running_processes": running_processes,
        "applied": apply,
        "actions": actions,
        "owned_runtime_roots": owned_roots,
        "pruned_directories": pruned,
    }
