from __future__ import annotations

from pathlib import Path

from .util import sha256_file


def encode_translation_text(text: str) -> str:
    """Encode exactly like XUnity AutoTranslator 5.6.1 TextHelper.Encode."""
    result: list[str] = []
    index = 0
    while index < len(text):
        char = text[index]
        if char == "/" and index + 1 < len(text) and text[index + 1] == "/":
            result.extend(("\\/", "\\/"))
            index += 2
            continue
        if char == "\\":
            result.append("\\\\")
        elif char == "=":
            result.append("\\=")
        elif char == "\n":
            result.append("\\n")
        elif char == "\r":
            result.append("\\r")
        else:
            result.append(char)
        index += 1
    return "".join(result)


def decode_translation_line(line: str) -> tuple[str, str] | None:
    """Small Python equivalent of XUnity's translation-line parser for tests."""
    parts: list[str] = []
    builder: list[str] = []
    index = 0
    while index < len(line):
        char = line[index]
        if char == "\\" and index + 1 < len(line):
            index += 1
            escaped = line[index]
            builder.append({"n": "\n", "r": "\r"}.get(escaped, escaped))
        elif char == "=":
            if parts:
                return None
            parts.append("".join(builder))
            builder.clear()
        elif char == "/" and index + 1 < len(line) and line[index + 1] == "/":
            break
        else:
            builder.append(char)
        index += 1
    if len(parts) != 1:
        return None
    return parts[0], "".join(builder)


def write_translation_file(path: Path, pairs: list[tuple[str, str]], title: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write(f"// {title}\n")
        stream.write("// Generated offline from matched official locale data.\n")
        for source, target in pairs:
            stream.write(encode_translation_text(source))
            stream.write("=")
            stream.write(encode_translation_text(target))
            stream.write("\n")


def validate_translation_pack(pack_root: Path) -> dict[str, object]:
    text_root = pack_root / "Translation" / "zh" / "Text"
    if not text_root.is_dir():
        raise FileNotFoundError(f"Translation text directory not found: {text_root}")
    files: list[dict[str, object]] = []
    errors: list[dict[str, object]] = []
    seen: dict[str, tuple[str, str, int]] = {}
    total = 0
    for path in sorted(text_root.glob("*.txt")):
        file_lines = 0
        for line_number, line in enumerate(
            path.read_text(encoding="utf-8-sig").splitlines(), start=1
        ):
            if not line or line.lstrip().startswith("//"):
                continue
            parsed = decode_translation_line(line)
            if parsed is None or not parsed[0] or not parsed[1]:
                errors.append(
                    {"file": path.name, "line": line_number, "error": "malformed mapping"}
                )
                continue
            source, target = parsed
            previous = seen.get(source)
            if previous is not None and previous[0] != target:
                errors.append(
                    {
                        "file": path.name,
                        "line": line_number,
                        "error": "conflicting duplicate source",
                        "previous_file": previous[1],
                        "previous_line": previous[2],
                    }
                )
                continue
            seen[source] = (target, path.name, line_number)
            file_lines += 1
            total += 1
        files.append(
            {
                "name": path.name,
                "bytes": path.stat().st_size,
                "sha256": sha256_file(path),
                "mappings": file_lines,
            }
        )
    return {
        "ok": not errors and bool(files),
        "pack_root": str(pack_root.resolve()),
        "mappings": total,
        "unique_sources": len(seen),
        "files": files,
        "error_count": len(errors),
        "errors": errors[:100],
    }


def offline_config(source_locale: str, font_name: str = "") -> str:
    if source_locale not in {"en", "jp"}:
        raise ValueError(f"Unsupported source locale: {source_locale}")
    fallback_font = font_name.strip()
    from_language = {"en": "en", "jp": "ja"}[source_locale]
    return f"""[Service]
Endpoint=
FallbackEndpoint=

[General]
Language=zh
FromLanguage={from_language}

[Files]
Directory=Translation\\{{Lang}}\\Text
OutputFile=Translation\\{{Lang}}\\Text\\_AutoGeneratedTranslations.txt
SubstitutionFile=Translation\\{{Lang}}\\Text\\_Substitutions.txt
PreprocessorsFile=Translation\\{{Lang}}\\Text\\_Preprocessors.txt
PostprocessorsFile=Translation\\{{Lang}}\\Text\\_Postprocessors.txt

[TextFrameworks]
EnableUGUI=True
EnableNGUI=False
EnableTextMeshPro=True
EnableTextMesh=False
EnableIMGUI=False
EnableFairyGUI=False

[Behaviour]
MaxCharactersPerTranslation=400
UseStaticTranslations=True
OverrideFont=
OverrideFontTextMeshPro=
FallbackFontTextMeshPro={fallback_font}
EnableUIResizing=True
ForceUIResizing=False
EnableBatching=False
EnableTranslationScoping=True
EnableTextPathLogging=False
OutputUntranslatableText=False
HandleRichText=True
PersistRichTextMode=Final

[Texture]
EnableTextureTranslation=False
EnableTextureDumping=False
EnableTextureToggling=False

[ResourceRedirector]
EnableTextAssetRedirector=False
EnableDumping=False
LogAllLoadedResources=False

[Http]
DisableCertificateValidation=False
"""
